### ISSUE TITLE
Lack of M files

### ISSUE THREAD

**Issue by HaoWangCyy** [FredericWantiez/Cahn-Hilliard-solver#1]
hfun = @cross_initial_bis, when I download it, I can't run it,There is no m file in the program!

**Comment by FredericWantiez** [comment]
Pushed the file, should be working now !
This file just defines an initial condition on the grid, you can use whatever you want at this step.

**Comment by HaoWangCyy** [comment]
Thanks a lot！I find there is lack of  m file of cross_initial.

**Comment by HaoWangCyy** [comment]
Hellow professor！ I'm sorry to border you again. I find it is also lack of interpolate_fem.m and do you have an article on this code? If you have, could you send me the article by e-mail-wanghao106031@126.com ? I want to study further.
Everything goes well with your work.
Be in good health.
